/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/clown.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    // console.log(actions);
    actions.look.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.05, 0.05]}
        position={[0, -1, 1]}
      >
        <primitive object={nodes.Hips} />
        <skinnedMesh
          material={materials.WhiteClown_material}
          geometry={nodes.WhiteClown.geometry}
          skeleton={nodes.WhiteClown.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/clown.glb");
